export default {
  colors: {
    primary: "#FFFFFF",
    secondary: "#7C7C7C",
    secondary_light: "#FD595845",
    success: "#34C38F",
    success_light: "#FFE1E0",
    yellow: "#FAC12F",
    attention_light: "#EDEDED7E",
    shape: "#858585",
    title: "#CDCDD0",
    text: "#495057",
    background: "#F5F4F7",
    backgroud_input: "#F9F9F9",
    border_input: "#E6E6E6",
    color_input: "#A2A2A2",
    dark: "#3C3C3C",
    red: "#F54A48",
    blue: "#858585",
    grey: "#EBEBEB",
  },
  fonts: {
    light: "Poppins_300Light",
    regular: "Poppins_400Regular",
    bold: "Poppins_700Bold",
    medium: "Poppins_500Medium",
    extra_bold: "Poppins_800ExtraBold",
    poppins_semiBold: "Poppins_SemiBold",
  },
};
